Update

diff --git a/helpers/node-bmw-client b/helpers/node-bmw-client
--- a/helpers/node-bmw-client
+++ b/helpers/node-bmw-client
@@ -3,21 +3,17 @@
 
 #### Variables ==start ####
 
-export PATH="/bin:/usr/bin"
+export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
 
-UNIT="node-bmw-client"
+APP="$(basename ${0})"
+APP_DIR="$(dirname $(readlink -f ${0}) | sed 's/\/helpers//g')"
+APP_FILE="${APP_DIR}/main.js"
 
-DIR_SYSTEMD="/etc/systemd/system"
+SYSTEMD_DIR="/etc/systemd/system"
+SYSTEMD_APP="${APP}.service"
+SYSTEMD_APP_FILE="${SYSTEMD_DIR}/${SYSTEMD_APP}"
 
-DIR_APP="/usr/local/${UNIT}"
-[[ -d ${HOME}/code/${UNIT} ]] && DIR_APP="${HOME}/code/${UNIT}"
-
-FILE_APP="${DIR_APP}/main.js"
-
-SYSTEMD_UNIT="${UNIT}.service"
-SYSTEMD_UNIT_FILE="${DIR_SYSTEMD}/${SYSTEMD_UNIT}"
-
-OLD_PWD=${PWD}
+UNAME="$(uname)"
 
 #### Variables ==final ####
 
@@ -25,7 +21,8 @@ OLD_PWD=${PWD}
 #### Functions ==start ####
 
 log() {
-	sudo logger -s -t "${UNIT}" "${1}" 2>&1
+	[[ "${UNAME}" != "Linux" ]] && return
+	sudo logger -s -t "${APP}" "${1}" 2>&1
 }
 
 sleep_msg() {
@@ -35,24 +32,27 @@ sleep_msg() {
 
 debug() {
 	stop > /dev/null 2>&1
-	/usr/bin/env node --trace-warnings --preserve-symlinks ${FILE_APP}
+	/usr/bin/env node --trace-warnings --preserve-symlinks ${APP_FILE}
 }
 
 launch() {
 	stop > /dev/null 2>&1
-	/usr/bin/env node --throw-deprecation --trace-warnings --preserve-symlinks ${FILE_APP}
+	/usr/bin/env node --throw-deprecation --trace-warnings --preserve-symlinks ${APP_FILE}
 }
 
 follow() {
-	sudo journalctl -u ${UNIT} -f -n 5 | sed "s/$(hostname -s)\ ${UNIT}\[.*.]:\ //g"
+	[[ "${UNAME}" != "Linux" ]] && return
+	sudo journalctl -u ${APP} -f -n 5 | sed "s/$(hostname -s)\ ${APP}\[.*.]:\ //g"
 }
 
 status() {
-	echo -e "Checking status of ${UNIT}\n"
-	sudo systemctl status ${UNIT}
+	[[ "${UNAME}" != "Linux" ]] && return
+	echo -e "Checking status of ${APP}\n"
+	sudo systemctl status ${APP}
 }
 
 restart() {
+	[[ "${UNAME}" != "Linux" ]] && return
 	stop
 	sleep_msg
 	start
@@ -61,9 +61,10 @@ restart() {
 }
 
 uninstall() {
-	log "Uninstalling ${SYSTEMD_UNIT}"
-	if [[ -s ${SYSTEMD_UNIT_FILE} ]]; then
-		if ! sudo rm -f ${SYSTEMD_UNIT_FILE}; then
+	[[ "${UNAME}" != "Linux" ]] && return
+	log "Uninstalling ${SYSTEMD_APP}"
+	if [[ -s ${SYSTEMD_APP_FILE} ]]; then
+		if ! sudo rm -f ${SYSTEMD_APP_FILE}; then
 			log "Failed to remove existing systemd unit file, cannot continue"
 			exit 1
 		fi
@@ -78,15 +79,16 @@ uninstall() {
 }
 
 install() {
-	log "Installing ${SYSTEMD_UNIT}"
-	if [[ -s ${SYSTEMD_UNIT_FILE} ]]; then
-		if ! sudo rm -f ${SYSTEMD_UNIT_FILE}; then
+	[[ "${UNAME}" != "Linux" ]] && return
+	log "Installing ${SYSTEMD_APP}"
+	if [[ -s ${SYSTEMD_APP_FILE} ]]; then
+		if ! sudo rm -f ${SYSTEMD_APP_FILE}; then
 			log "Failed to remove existing systemd unit file, cannot continue"
 			exit 1
 		fi
 	fi
 
-	if ! sudo cp ${DIR_APP}/helpers/${SYSTEMD_UNIT} ${SYSTEMD_UNIT_FILE}; then
+	if ! sudo cp ${APP_DIR}/helpers/${SYSTEMD_APP} ${SYSTEMD_APP_FILE}; then
 		log "Failed to copy systemd unit file, cannot continue"
 		exit 2
 	fi
@@ -100,101 +102,103 @@ install() {
 }
 
 disable() {
-	if ! sudo systemctl -q is-enabled ${SYSTEMD_UNIT}; then
-		log "${SYSTEMD_UNIT} is already disabled"
+	[[ "${UNAME}" != "Linux" ]] && return
+	if ! sudo systemctl -q is-enabled ${SYSTEMD_APP}; then
+		log "${SYSTEMD_APP} is already disabled"
 		return
 	fi
 
-	log "Disabling ${SYSTEMD_UNIT}"
-	sudo systemctl disable ${SYSTEMD_UNIT}
+	log "Disabling ${SYSTEMD_APP}"
+	sudo systemctl disable ${SYSTEMD_APP}
 	sleep_msg
 
-	if ! sudo systemctl -q is-enabled ${SYSTEMD_UNIT}; then
-		log "Disabled ${SYSTEMD_UNIT} successfully"
+	if ! sudo systemctl -q is-enabled ${SYSTEMD_APP}; then
+		log "Disabled ${SYSTEMD_APP} successfully"
 	else
-		log "Failed to disable ${SYSTEMD_UNIT}"
+		log "Failed to disable ${SYSTEMD_APP}"
 	fi
 }
 
 enable() {
-	if sudo systemctl -q is-enabled ${SYSTEMD_UNIT}; then
-		log "${SYSTEMD_UNIT} is already enabled"
+	[[ "${UNAME}" != "Linux" ]] && return
+	if sudo systemctl -q is-enabled ${SYSTEMD_APP}; then
+		log "${SYSTEMD_APP} is already enabled"
 		return
 	fi
 
-	if [[ ! -s ${SYSTEMD_UNIT_FILE} ]]; then
+	if [[ ! -s ${SYSTEMD_APP_FILE} ]]; then
 		install
 	fi
 
-	log "Enabling ${SYSTEMD_UNIT}"
-	sudo systemctl enable ${SYSTEMD_UNIT}
+	log "Enabling ${SYSTEMD_APP}"
+	sudo systemctl enable ${SYSTEMD_APP}
 	sleep_msg
 
-	if sudo systemctl -q is-enabled ${SYSTEMD_UNIT}; then
-		log "Enabled ${SYSTEMD_UNIT} successfully"
+	if sudo systemctl -q is-enabled ${SYSTEMD_APP}; then
+		log "Enabled ${SYSTEMD_APP} successfully"
 	else
-		log "Failed to enable ${SYSTEMD_UNIT}"
+		log "Failed to enable ${SYSTEMD_APP}"
 	fi
 }
 
 stop() {
-	if ! sudo systemctl -q is-active ${SYSTEMD_UNIT}; then
-		log "${SYSTEMD_UNIT} is already inactive"
+	[[ "${UNAME}" != "Linux" ]] && return
+	if ! sudo systemctl -q is-active ${SYSTEMD_APP}; then
+		log "${SYSTEMD_APP} is already inactive"
 		return
 	fi
 
-	log "Stopping ${SYSTEMD_UNIT}"
-	sudo systemctl stop ${SYSTEMD_UNIT}
+	log "Stopping ${SYSTEMD_APP}"
+	sudo systemctl stop ${SYSTEMD_APP}
 	sleep_msg
 
-	if ! sudo systemctl -q is-active ${SYSTEMD_UNIT}; then
-		log "Stopped ${SYSTEMD_UNIT} successfully"
+	if ! sudo systemctl -q is-active ${SYSTEMD_APP}; then
+		log "Stopped ${SYSTEMD_APP} successfully"
 	else
-		log "Failed to stop ${SYSTEMD_UNIT}"
+		log "Failed to stop ${SYSTEMD_APP}"
 		echo
 		status
 	fi
 }
 
 start() {
-	if sudo systemctl -q is-active ${SYSTEMD_UNIT}; then
-		log "${SYSTEMD_UNIT} is already active"
+	[[ "${UNAME}" != "Linux" ]] && return
+	if sudo systemctl -q is-active ${SYSTEMD_APP}; then
+		log "${SYSTEMD_APP} is already active"
 		return
 	fi
 
-	log "Starting ${SYSTEMD_UNIT}"
-	sudo systemctl start ${SYSTEMD_UNIT}
+	log "Starting ${SYSTEMD_APP}"
+	sudo systemctl start ${SYSTEMD_APP}
 	sleep_msg
 
-	if sudo systemctl -q is-active ${SYSTEMD_UNIT}; then
-		log "Started ${SYSTEMD_UNIT} successfully"
+	if sudo systemctl -q is-active ${SYSTEMD_APP}; then
+		log "Started ${SYSTEMD_APP} successfully"
 	else
-		log "Failed to start ${SYSTEMD_UNIT}"
+		log "Failed to start ${SYSTEMD_APP}"
 		echo
 		status
 	fi
 }
 
 update() {
-	cd ${DIR_APP}
+	cd ${APP_DIR}
 
 	GIT_BRANCH="$(git branch | grep '*' | sed 's/^*\ //g')"
 	git fetch origin ${GIT_BRANCH} &> /dev/null
 
 	GIT_LOG="$(git log HEAD..origin/${GIT_BRANCH} --oneline)"
-	[[ -z "${GIT_LOG}" ]] && log "No ${UNIT} update needed" && return
+	[[ -z "${GIT_LOG}" ]] && log "No ${APP} update needed" && return
 
-	log "${UNIT} update available!"
+	log "${APP} update available"
 
-	log "Downloading ${UNIT} update"
+	log "Downloading ${APP} update"
 	git pull
 
 	log "Performing npm install"
 	npm install
 
 	restart
-
-	cd ${OLD_PWD}
 }
 
 #### Functions ==final ####
